* Введение
** 1. Общие замечания
*** Кем были французские революционеры?
Не смотря на то, что французские революционеры подвергли все аспекты человеческой кульутры жесточайшей критики, они оставались буржуа и весь идеал -- это царствие буржуа.

Буржуа были эксплуатируемыми а эксплуататорами были дворяне. Таким образом буржуа отстаивали интересы эксплуатируемых.

Интересно рассуждать над историей, как над чем-то цикличным -- некой спиралью. Были монархи, потом дворяне, потом буржуа, а кто потом?

*** Вы не готовы!
#+BEGIN_QUOTE
Истинный разум и истинная справедливость до сих пор не господствовали в мире только потому, что они не были еще надлежащим образом познаны
#+END_QUOTE

Тоже интересная, но грустная мысль. Коммунисты хотели блага для обычных людей -- занятия собственным развитием и т.д. Но люди оказались к этому не готовы.

*** Метафизика
#+BEGIN_QUOTE
Для метафизика вещи и их мысленные отражения, понятия, суть отдельные, неизменные, застывшие, раз навсегда данные предметы, подлежащие застывшие, раз навсегда данные предметы, подлежащие исследованию один после другого и один независимо от другого.
#+END_QUOTE

Автор озвучил эту мысль после того, как объяснял "осознание" природы как нечто огромное, обладающее оргромным количеством связей и все они тесно переплетены и движутся, меняются, а естествознание занимается тем, что рассматривает эти связи обособленно.

*** Диалектика
#+BEGIN_QUOTE
Для диалектики же, для которой существенно то, что она берет вещи и их умственные отражения в их взаимной связи, в их сцеплении, в их движении, в их возникновении и исчезновении
#+END_QUOTE

Приведено отличие от метафизики. Можно ли назвать любое размышление о природе, как нечте целом, или размышлении о каком-то явлении в совокупности со всеми остальными, диалектикой? Или есть еще какие-то условия?
*** Материализм
#+BEGIN_QUOTE
...современный материализм видит в истории процесс развития человечества и ставит своей задачей открытие законов движения этого процесса.
#+END_QUOTE

*** Идеализм
Материализм как противник идеализму, а идеализм это
#+BEGIN_QUOTE
Гегель был идеалист, т. е. для него мысли нашей головы были не отражениями, более или менее абстрактными, действительных вещей и процессов, а, наоборот, вещи и развитие их были для Гегеля лишь воплотившимися отражениями какой-то «идеи», существовавшей где-то еще до возникновения мира
#+END_QUOTE

Возможно идеализм, это попытка объяснить цель чего либо неким "предназначением", которое, по мнение этой теории, есть у каждой вещи. Материализм пытаеться объяснить это с материальной - естественнонаучной - точки зрения, а идеализм у всего пытается найти некую идею.

*** Еще про материализм
#+BEGIN_QUOTE
был найден путь для объяснения сознания людей из их бытия вместо прежнего объяснения их бытия из их сознания
#+END_QUOTE

Последнее -- это про идеализм.

Автор говорит о прежнем социализме -- видимо имеется ввиду социализм, основанный не на материалистической и диалектической картине мира, в которой все объясняется идеализмом. То есть база этого прежнего социализма -- поиск некой цели и сверъестественных объяснений.

В то время как социализм, основанный на материализме, объясняет все с естественной точки зрения -- что-то в истории было вынужденно временем, что-то экономикой, то есть реальными вещами, а не какими-то вымыслами. И в дальейшем критика пойдет именно в сторону такого, не научного, социализма.

