* Введение
** 1. Общие замечания
*** Кем были французские революционеры?
Не смотря на то, что французские революционеры подвергли все аспекты человеческой кульутры жесточайшей критики, они оставались буржуа и весь идеал -- это царствие буржуа.

Буржуа были эксплуатируемыми а эксплуататорами были дворяне. Таким образом буржуа отстаивали интересы эксплуатируемых.

Интересно рассуждать над историей, как над чем-то цикличным -- некой спиралью. Были монархи, потом дворяне, потом буржуа, а кто потом?

*** Вы не готовы!
#+BEGIN_QUOTE
Истинный разум и истинная справедливость до сих пор не господствовали в мире только потому, что они не были еще надлежащим образом познаны
#+END_QUOTE

Тоже интересная, но грустная мысль. Коммунисты хотели блага для обычных людей -- занятия собственным развитием и т.д. Но люди оказались к этому не готовы.

*** Метафизика
#+BEGIN_QUOTE
Для метафизика вещи и их мысленные отражения, понятия, суть отдельные, неизменные, застывшие, раз навсегда данные предметы, подлежащие застывшие, раз навсегда данные предметы, подлежащие исследованию один после другого и один независимо от другого.
#+END_QUOTE

Автор озвучил эту мысль после того, как объяснял "осознание" природы как нечто огромное, обладающее оргромным количеством связей и все они тесно переплетены и движутся, меняются, а естествознание занимается тем, что рассматривает эти связи обособленно.

*** Диалектика
#+BEGIN_QUOTE
Для диалектики же, для которой существенно то, что она берет вещи и их умственные отражения в их взаимной связи, в их сцеплении, в их движении, в их возникновении и исчезновении
#+END_QUOTE

Приведено отличие от метафизики. Можно ли назвать любое размышление о природе, как нечте целом, или размышлении о каком-то явлении в совокупности со всеми остальными, диалектикой? Или есть еще какие-то условия?
*** Материализм
#+BEGIN_QUOTE
...современный материализм видит в истории процесс развития человечества и ставит своей задачей открытие законов движения этого процесса.
#+END_QUOTE

*** Идеализм
Материализм как противник идеализму, а идеализм это
#+BEGIN_QUOTE
Гегель был идеалист, т. е. для него мысли нашей головы были не отражениями, более или менее абстрактными, действительных вещей и процессов, а, наоборот, вещи и развитие их были для Гегеля лишь воплотившимися отражениями какой-то «идеи», существовавшей где-то еще до возникновения мира
#+END_QUOTE

Возможно идеализм, это попытка объяснить цель чего либо неким "предназначением", которое, по мнение этой теории, есть у каждой вещи. Материализм пытаеться объяснить это с материальной - естественнонаучной - точки зрения, а идеализм у всего пытается найти некую идею.

*** Еще про материализм
#+BEGIN_QUOTE
был найден путь для объяснения сознания людей из их бытия вместо прежнего объяснения их бытия из их сознания
#+END_QUOTE

Последнее -- это про идеализм.

Автор говорит о прежнем социализме -- видимо имеется ввиду социализм, основанный не на материалистической и диалектической картине мира, в которой все объясняется идеализмом. То есть база этого прежнего социализма -- поиск некой цели и сверъестественных объяснений.

В то время как социализм, основанный на материализме, объясняет все с естественной точки зрения -- что-то в истории было вынужденно временем, что-то экономикой, то есть реальными вещами, а не какими-то вымыслами. И в дальейшем критика пойдет именно в сторону такого, не научного, социализма.

** 2. Что обещает г-н Дюринг
* Отдел первый. Философия
** 3. Подразделение. Априоризм
*** Мышление и сознание
#+BEGIN_QUOTE
...должно показаться чрезвычайно удивительным то обстоятельство, что сознание и природа, мышление и бытие, законы мышления и законы природы до такой степени согласуются между собой. Но если, далее, поставить вопрос, что же такое мышление и сознание, откуда они берутся, то мы увидим, что они – продукты человеческого мозга и что сам человек – продукт природы, развившийся в определенной среде и вместе с ней.
#+END_QUOTE

Это к слову о том, что философы-идеалисты (и не только они) пытаются объяснить природу исключительно умственным путем, не прибегаю к экспериментам.
*** Про бога
#+BEGIN_QUOTE
Мы увидим впоследствии, что г-н Дюринг вынужден неоднократно подсовывать природе сознательный образ действий, т. е. попросту говоря – бога.
#+END_QUOTE

Просто отметил это интересным.
*** Положительная наука > философия
#+BEGIN_QUOTE
Если схематику мира выводить не из головы, а только при помощи головы из действительного мира, если принципы бытия выводить из того, что есть, – то для этого нам нужна не философия, а положительные знания о мире и о том, что в нем происходит...
#+END_QUOTE

Полностью согласен.
*** Полная картина мира
#+BEGIN_QUOTE
Если бы в какой-нибудь момент развития человечества была построена подобная окончательно завершенная система всех мировых связей, как физических, так и духовных и исторических, то тем самым область человеческого познания была бы завершена, и дальнейшее историческое развитие прервалось бы с того момента, как общество было бы устроено в соответствии с этой системой, – а это было бы абсурдом, чистой бессмыслицей
#+END_QUOTE

Не понимаю почему это абсурдно.
*** Математика
Также стоит затронуть здесь тему математики, и что она может быть чиста от экспериментов и выведена строго из мышления.

Это неправда хотябы потому, что ,опять-таки, мышление это продукт реального мира.

Ну а такие абстракции математики, как числа и фигуры, также являются продуктом реального мира хотя бы потому, что люди, которые придумали математику и ввели числа и фигуры, сделали это на базе реальных подсчетов (10 пальцев) и реальных фигур. То есть была потребность в счете -- появилась абстракция числа.

К вопросу о том, что "математики имеет значение независимое от особого опыта каждой отдельной личности" и что "то же самое можно сказать о всех твердо установленных факстах любой науки и даже о всех фактах вообще", то я здесь также согласен.

Все в мире подчиняется некоторым общим законам -- самая абстрактная часть этих законов и есть математика. Ну а вывели эти законы опытным путем, а не из чистого разума.
** 4. Мировая схематика
*** Единство
#+BEGIN_QUOTE
...мышление, если оно не делает промахов, может объединить элементы сознания в некоторое единство лишь в том случае, если в них или в их реальных прообразах это единство уже до этого существовало.
#+END_QUOTE
И пример
#+BEGIN_QUOTE
Оттого, что сапожную щетку мы зачислим в единую категорию с млекопитающими, – от этого у нее еще не вырастут молочные железы.
#+END_QUOTE
Это к слову о том, как идеалисты мыслят о единстве бытия -- это очень интересно:
1. я мыслю бытие
2. эта мысль едина (чтобы это не значило)
3. мышление и бытие должно находится в согласии. Это про то, что идеалисты мыслят, что все, что может породить их мышление, должно быть отражено в бытие. Если это укладывается в голове, то так и должно быть.
4. следовательно, если мысль едина, то и бытие тоже

Именно к этому приводит рассуждения о природе вещей без опытного подтверждения -- рассуждение о вещах в отрыве от них самих, тем самым разделяя реальные вещи от представления об этих вещах.
*** Единство мира
#+BEGIN_QUOTE
Единство мира состоит не в его бытии, хотя его бытие есть предпосылка его единства, ибо сначала мир должен существовать, прежде чем он может быть единым. Бытие есть вообще открытый вопрос, начиная с той границы, где прекращается наше поле зрения. Действительное единство мира состоит в его материальности, а эта последняя доказывается не парой фокуснических фраз, а длинным и трудным развитием философии и естествознания.
#+END_QUOTE
** 5. Натурфилософия. Время и пространство
Бесконечность складывается из конечных величин.
*** Дюринг, Кант и конечный мир
В начале Дюринг пытается доказать что мир имеет границы (количество материи орграничено) и берет начало во времени (отправная точка).

Доказывает он это не самым очевидным образом, на сколько я понял начало во времени доказывается тем, что если бы не было начала, то была бы бесконечность до текущего момента -- а это по его мнение противоречие (сосчитанный бесконечный ряд).

От чего то Дюринг мыслит бесконечность как бесконечный ряд -- пространство с одним измерением.

Доказательство ограниченности мира я так и не понял.

Автор утдверждает, что это калька с Канта (Критика чистого разума), а сам Кант, сразу же после этого, доказывает обратное и видит в этом большое противоречие.

*** Бесконечность
На самом деле глупо полагать, что бесконечность это бесконечный ряд. Как отметил автор
#+BEGIN_QUOTE
...тут нет конца ни в какую сторону, – ни вперед, ни назад, ни вверх, ни вниз, ни вправо, ни влево. Эта бесконечность совершенно иная, чем та, которая присуща бесконечному ряду, ибо последний всегда начинается прямо с единицы, с первого члена ряда.
#+END_QUOTE
и я с ним полностью согласен.

Также бесконечный ряд невозможно применить при определении бесконечности пространства так как пространство все таки имеет минимум 3 измерения.

*** Бесконечность времени
#+BEGIN_QUOTE
В применении ко времени бесконечная в обе стороны линия, или бесконечный в обе стороны ряд единиц, имеет известный образный смысл. Но если мы представляем себе время как ряд, начинающийся с единицы, или как линию, выходящую из определенной точки, то мы тем самым уже заранее говорим, что время имеет начало; мы предполагаем как раз то, что должны доказать. Мы придаем бесконечности времени односторонний, половинчатый характер; но односторонняя, разделенная пополам бесконечность есть также противоречие в себе, есть прямая противоположность «бесконечности, мыслимой без противоречий». Избежать такого противоречия можно лишь приняв, что единицей, с которой мы начинаем считать ряд, точкой, отправляясь от которой мы производим измерение линии, может быть любая единица в ряде, любая точка на линии и что для линии или ряда безразлично, где мы поместим эту единицу или эту точку.
#+END_QUOTE
Сейчас я не в состоянии полностью понять этот отрывок, поэтому сохряню его здесь.
*** Сосчитанный бесконечный ряд
Очередной бред. Представим интервал между -бескоеечность и 0 -- возможно ли его сосчитать? Ведь за какое число не возьмись, позади себя ты оставишь бесконечность.
*** Бесконечность с началом
Было какое-то противопостовление между бесконечностью с началом (или с концом) и бесконечностью без начала и конца -- в каком-то смысле да, это разные вещи. Вторая бесконечность "расплывается" в оба направления, но первая бесконечность, от того что она "расплывается" лишь в обном напралвении, не становится менее бесконечной.
*** Так конечен мир или нет?
По мнению автора любой из ответов на этот вопрос вызывает противоречия. 
#+BEGIN_QUOTE
Ограниченность материального мира приводит к не меньшим противоречиям, чем его безграничность, и всякая попытка устранить эти противоречия ведет, как мы видели, к новым и худшим противоречиям. Именно потому, что бесконечность есть противоречие, она представляет собой бесконечный, без конца развертывающийся во времени и пространстве процесс. Уничтожение этого противоречия было бы концом бесконечности.
#+END_QUOTE
*** Время
#+BEGIN_QUOTE
Бытие вне времени есть такая же величайшая бессмыслица, как бытие вне пространства.
#+END_QUOTE

Так как эти две вещи очень тесно связанны, то 

Вот человек, по моему в его сущности мыслить пространство как нечто конечное, а время, как что-то из начала. Сложно человеку помылсить бесконечность, но бесконечный ряд (время) еще можно. Так может быть эта ограниченность в том, что мы мыслим просто не так? Мы разбиваем эти два понятия -- время и пространство, в то время, как они зависят друг от друга и являются одним целым.

И кстати, вспомни время по Фейнману -- нечто, разделяющее два последовательных события. Но может ли что-то произойти в пустоте, произойти без пространства?
*** Начало мира из равновесия?
Дюринг говорит, что изначально мир был в полном равновессии, все силы были скоменсированны и что нечтно из вне дало изначальный импульс.

Естествознание пытается объяснить это другим путем, ссылая этот изначальный импульс на события до полного равновесия.

#+BEGIN_QUOTE
Установление отдельных переходов и связей всех, даже самых малых, звеньев в цепи бытия как раз и составляет содержание естествознания, и если при этом кое-где дело не ладится, то никому, даже г-ну Дюрингу, не приходит в голову объяснять происшедшее движение из «ничего», а всегда, напротив, предполагается, что это движение является результатом перенесения, преобразования или продолжения какого-нибудь предшествующего движения
#+END_QUOTE
** 6. Натурфилософия. Космогония, физика, химия
*** Кант, мир из тумманности
#+BEGIN_QUOTE
Кантовская теория возникновения всех теперешних небесных тел из вращающихся туманных масс была величайшим завоеванием астрономии со времени Коперника. Впервые было поколеблено представление, будто природа не имеет никакой истории во времени. До тех пор считалось, что небесные тела с самого начала движутся по одним и тем же орбитам и пребывают в одних и тех же состояниях
#+END_QUOTE

Интересное замечание про то, что считалось, будто природа не иммет никакой истории во времени.

#+BEGIN_QUOTE
Было, конечно, очевидно для всех, что природа находится в постоянном движении, но это движение представлялось как непрестанное повторение одних и тех же процессов
#+END_QUOTE

Почему то приходит на ум предположение о цикличности истории.

*** Наблюдение тумманности
Интересно представить наблюдение первоночальной тумманости. Еще не существуте небесных тел, а значит нет звезд, а значит нет света, и как гипотетический бог мог наблюдать все это? Через всевидящее око? Но из квантовой физики мы знаем, что наблюдение есть вмешательство -- так вот какое оно "божественное вмещательство".

*** Дюринг и статичный изначальный мир
Дюринг говорит, что первоначальный мир пребывал в состоянии полного покоя без какого-либо движения. То есть вся материя была неподвижна -- "равное самому себе состояние материи". А затем что-то произошло и все задвигалось -- то есть бог.

Автор же говорит очень здравую мысль о том, что материя не может быть неподвижна -- "Движение есть способ существования материи". Это следует из физики.

Ну и также стоит отметить, что движение -- относительная вещь. Тело может покоиться в одной системе координат, но двигаться в другой. 

*** Материя и движение
#+BEGIN_QUOTE
Материя без движения так же немыслима, как и движение без материи. Движение поэтому так же несотворимо и неразрушимо, как и сама материя – мысль, которую прежняя философия (Декарт) выражала так: количество имеющегося в мире движения остается всегда одним и тем же. Следовательно, движение не может быть создано, оно может быть только перенесено.
#+END_QUOTE

Вау!

Проблема Дюринга в том, что он рассматривает только механическое движение материи, не рассматривая тепловое, эллектромагнитное и так далее.

Также Дюрингово первоночальное состояние материи можно рассматривать как заряженное ружье, которое покоиться, не движется, но содержит в себе большой потенциал. И получается что человек, который нажмет на спусковой крючок запустит мир начав движение. Но тогда следуют два вопроса:
- кто зарядил ружье?
- кто произвел выстрел?

#+BEGIN_QUOTE
Мы можем вертеться и изворачиваться, как нам угодно, но под руководством г-на Дюринга мы каждый раз опять возвращаемся к… персту божию.
#+END_QUOTE

*** Почему гипотезы вообще воспринимаются?
Ну во-первых всякий факт или теория начинаются с гипотезы и это просто один из шагов развития знания, но здесь речь не об этом.

#+BEGIN_QUOTE
Оно поэтому несомненно полно пробелов, как и вообще вся эта еще очень молодая теория, но, по крайней мере, эта гипотеза может объяснить данный процесс, не вступая в какое бы то ни было противоречие с неуничтожимостью и несотворимостью движения, и она даже в состоянии дать точный отчет о том, куда девается теплота во время ее превращения.
#+END_QUOTE

Как понять что гипотеза представляет ценность? Она ложиться в картину мира и объясняет свой предмет.

*** Главный вопрос: статическое -> динамическое
Одним из самых интересных вопросов на проятжении уже двух глав является переход статической материи в динамическую.

Дюринг объясняет это изначальный толчком -- то есть богом.

Автор говорит, что материя по определению не может быть статической.

Я же тоже придерживаюсь того, что материя не может пребывать в спокойствии из-за внутреннего движения, а изначальный толчком послужила флуктуация и получается что наш настойщий мир есть полная случайность.

Конечно флуктуацию системе где столько переменных сложно назвать случайной -- уж слишком большая вероятность, но все же.

Не отвеченным остается вопрос "откуда взялась материя", но кажется мне, что наука никогда не ответит на этот вопрос.
